name: custom-alignment-pipeline
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.11
  - bowtie2=2.5.4
  - samtools=1.23.1
  - bioconductor-deseq2=1.50.2
  - r-argparse=2.3.1
